### ISSUE TITLE
Add backend for print_label.py

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#10]
print_label.py is a quick hack now using the box-terminator api. Consider to create a memberbooth endpoint in backend that can deliver the same object as the present one does but with the member_number as input instead.

**Comment by emanuelen5** [comment]
Backend addition: makerspace/makeradmin@934a249b55e1dbad4238d6636ded93e1529df11d
Corresponding memberbooth change: 6db2b023069d4f19ec48dc68f1c9349349c91f54

**Comment by emanuelen5** [comment]
Will be solved by pull request #30
