### ISSUE TITLE
Warning labels for member boxes

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#102]
We need some labels to put on member boxes that will be terminated in a few weeks time so that it is easy to empty boxes. Need to assess in what way and which boxes. But the script must be easily accessible, preferably by the label_printer user. 

Also the print waring label should be made accessible for the label_printer user.

**Comment by emanuelen5** [comment]
This has been fixed https://github.com/makerspace/memberbooth/blob/193a2656f2d06d4109684496dbaa1792a782599a/print_warning_label.py
