### ISSUE TITLE
Implement selective input to login entry.

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#16]
Login entry should only get input from certain USB-devices.

Not keyboard, only RFID-reader.

**Comment by InMyOrbit** [comment]
We could argue that this is not a problem since issue #21 was solved.

**Comment by emanuelen5** [comment]
This might still be fun to implement if we have our own custom RFID reader

**Comment by emanuelen5** [comment]
Won't fix for now
