### ISSUE TITLE
Assess use of brother_ql - deprecated messages at software start. 

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#18]

**Comment by emanuelen5** [comment]
I do not think this is an issue.

1. The deprecation has been removed in the current version (it was removed in this commit pklaus/brother_ql@5c2b72b18bcf436c116f180a9147cbb6805958f5).
2. I pegged the version of the brother_ql package to 6.1 (see 9f1fbb0b113b1b0b4d5535958cb8043f11e73fdf).
