### ISSUE TITLE
Remove HID implementation of tag_id read. 

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#34]
The first assumption was that we would have a RFID-reader with a USB HID implementation (keyboard). The code in this issue (and some more) is relating to that, but it was decided to leave it in the repository to have support for the proprietary RFID-reader.

https://github.com/makerspace/memberbooth/blob/59998ba7b481b0c35f429ab5e2bc7a9d140800cd/src/gui/design.py#L130-L181

**Comment by emanuelen5** [comment]
As discussed in [the comment section on PR #35](https://github.com/makerspace/memberbooth/pull/35#discussion_r292645994), I think we actually should keep this functionality. It could however be added as a separate flag where one can choose the input source for the tag reader.
