### ISSUE TITLE
System hanged after using unknown tag. 

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#49]

**Comment by InMyOrbit** [comment]
The issue is related to the following code, but I didn't manage to replicate the error without a tag reader. 

https://github.com/makerspace/memberbooth/blob/60f4a80dd9592ff9977777f96073dc4ec6b21d41/src/gui/states.py#L148-L167

**Comment by InMyOrbit** [comment]
Tried to raise the exception manually with Keyboard input and that worked just fine.

**Comment by emanuelen5** [comment]
[The timer for polling the reader is canceled here](https://github.com/makerspace/memberbooth/blob/master/src/gui/states.py#L109-L112) when a tag is read. It should only be canceled if the tag is also valid.
