### ISSUE TITLE
Lab membership actually shows yearly membership

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/memberbooth#54]

**Comment by emanuelen5** [comment]
The returned data from makeradmin is the culprit, specifically [this part](https://github.com/makerspace/makeradmin/blob/cdafb1ff8f/api/src/multiaccess/views.py#L49-L63)

**Comment by InMyOrbit** [comment]
@emanuelen5 Needs backend update to be fully fixed. Initial implementation in branch 53_54_Member_information_fix

**Comment by emanuelen5** [comment]
Backend fix in makerspace/makeradmin#126
